# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

# config/routes.yaml

api_routes:
    resource: './routes/api_routes.yaml'
    type: yaml

